version: "3.8"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./public:/var/www/public
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: project_nginx
        networks:
            - api

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./src:/var/www/src
        depends_on:
            - db
        container_name: project_app
        networks:
            - api
    db:
        image: postgres:14
        restart: always
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: user_api
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_INITDB_ARGS: --encoding=UTF8
        ports:
            - "8101:5432"
        container_name: project_db
        networks:
            - api
volumes:
    database:
networks:
    api:
